### ISSUE TITLE
Environment parameters - basic support

### ISSUE THREAD

**Issue by f3l1x** [nette/bootstrap#50]
This approach is taken from symfony, but I like it and I it's helpful in scaling application in Docker containers and so.

---

Example apache configuration.

```
<VirtualHost *:80>
    DocumentRoot    "/srv/nette/www"
    DirectoryIndex  index.php 
    SetEnv          NETTE__DATABASE__USER user
    SetEnv          NETTE__DATABASE__PASSWORD secret
</VirtualHost>
```

Or just container environment.

```
export NETTE__DATABASE__USER=user
export NETTE__DATABASE__PASSWORD=secret
```

You can use it in config.neon such as:

``` yaml
parameters:

database:
    dsn: 'mysql:host=%database.host%;dbname=%database.dbname%'
    user: %database.user%
    password: %database.password%
    options:
        lazy: yes
```

---

What do we need to do?

This is symfony method:

``` php
    protected function getEnvParameters()
    {
        $parameters = array();
        foreach ($_SERVER as $key => $value) {
            if (0 === strpos($key, 'SYMFONY__')) {
                $parameters[strtolower(str_replace('__', '.', substr($key, 9)))] = $value;
            }
        }
        return $parameters;
    }
```

I can rewrite it for Nette\Configurator.

Do you think@dg it can be part of configurator? Maybe it is a special function and should be in 3rd part libraries.
